version: 2.1
orbs:
  aws-s3: circleci/aws-cli@5.1.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - out

  deploy:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          role_arn: $AWS_ROLE_ARN
          region: $AWS_REGION
      - aws-cli/sync:
          from: out
          to: "s3://${AWS_S3_BUCKET_NAME}"
          arguments: |
            --delete

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
