import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { AppContextProvider } from '@/components/AppContext';
import ErrorAlert from '@/components/ErrorAlert';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import ThemeRegistry from '@/components/ThemeRegistry';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} style={{ colorScheme: 'dark' }}>
      <body>
        <AppContextProvider>
          <ThemeRegistry>
            <Header />
            {children}
            <ErrorAlert />
            <Footer />
          </ThemeRegistry>
        </AppContextProvider>
      </body>
    </html>
  );
}
